# Generated by Django 3.2.16 on 2022-12-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nic', models.CharField(max_length=12, verbose_name='NIC')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('wallet_address', models.CharField(help_text='Address of Etherium wallet', max_length=1024, verbose_name='Wallet Address')),
                ('img', models.ImageField(help_text='Portrait Image of the user', upload_to='', verbose_name='Image')),
                ('connection_id', models.UUIDField()),
                ('invite_url', models.URLField(max_length=2000)),
            ],
        ),
    ]
