# Generated by Django 3.2.16 on 2022-12-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='img',
            field=models.ImageField(blank=True, help_text='Portrait Image of the user', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Address of Etherium wallet', max_length=1024, null=True, verbose_name='Wallet Address'),
        ),
    ]
