# Generated by Django 3.2.16 on 2023-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0002_auto_20221221_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, null=True, verbose_name='Sex'),
        ),
    ]
